export const base_url = 'https://fortunetalk.co/fortunetalktest/'
export const api_url = 'https://fortunetalk.co/fortunetalktest/api/';
export const img_url = 'https://fortunetalk.co/fortunetalktest/admin/uploads/';
export const img_url_2 =
  'https://fortunetalk.co/fortunetalktest/admin/uploads/vendor/';
export const provider_img_url = 'https://fortunetalk.co/fortunetalktest/admin/';
//Customer

export const user_web_api_login = 'user_web_api/login?';
export const api2_get_countries = 'api2/get_countries';
export const api2_get_state = 'api2/get_state'; 
export const user_web_api_verification_otp = 'user_web_api/verification_otp?';
export const user_get_banner = 'user/get_banner.php';
export const api_astrolist1 = 'api/astrolist1';
export const api_astrodetails = 'api/astrodetails';
export const user_review = 'user/review.php?';
export const api_callintakesubmit = 'api/callintakesubmit';
export const api_callintake = 'api/callintake';
export const api_getastrochatstatus = 'api/getastrochatstatus';
export const api2_get_profile = 'api2/get_profile';
export const api_getRechargeplans = 'api/getRechargeplans';
export const user_chat_in = 'user/chat_in.php';
export const kundli_get_kundli = 'kundli/get_kundli';
export const api2_logout = 'api2/logout';
export const api_addwallet = 'api/addwallet';
export const api2_tarot_cards = 'api2/tarot_cards';
export const api_addreview = 'api/addreview';
export const api2_customer_date_profile = 'api2/customer_date_profile';
export const api2_is_customer_register = 'api2/is_customer_register';
export const api2_all_users = 'api2/all_users';
export const api2_myplans = 'api2/myplans';
export const api2_astrodate_plans = 'api2/astrodate_plans';
export const api2_subscriptions_purchase = 'api2/subscriptions_purchase';
export const api2_create_kundali = 'api2/create_kundali';
export const api2_my_kundali = 'api2/my_kundali';
export const kundli_get_panchang = 'kundli/get_panchang';
export const api2_get_chart = 'api2/get_chart';
export const kundli_get_planets = 'kundli/get_planets';
export const add_or_update_device_token =
  'Api_astro/add_or_update_device_token';
export const upload_customer_pic = 'user_web_api/upload_customer_pic';
export const accept_chat = 'api/accept_chat';
export const match_making = 'api2/match_making';
export const get_horoscope = 'api2/get_horoscope';
export const deductwallet = 'api/deductwallet';
export const order_history = 'api/order_history';
export const get_city = 'api2/get_city';
export const get_tarot_card_detail = 'api2/get_tarot_card_detail';
export const blog = 'api2/blog';
export const boost_profile = 'api2/boost_profile';
export const all_request = 'api2/all_request';
export const liked_me = 'api2/liked_me';
export const liked = 'api2/liked';
export const recommended_friends = 'api2/recommended_friends';
export const api_astro_call_to_astrologer = 'api_astro/call_to_astrologer';
export const get_profile = 'api2/get_profile';
export const customer_date_profile = 'api2/customer_date_profile';
export const get_notifications = 'api/getNotifications';
export const update_notifications = 'api/updateNotifications';
export const get_customer_date_profile = 'api2/get_customer_date_profile';
export const api_paymenthistory = 'api/paymenthistory';
export const api_getfollowinglist = 'api/getfollowinglist';
export const api_follow = 'api/follow';
export const api_checkfollowing = 'api/checkfollowing';
export const about_friend = 'api2/about_friend';
export const get_gifts = 'api2/get_gifts';
export const update_like = 'api2/update_like';
export const customer_date_images_upload = 'api2/customer_date_images_upload';
export const get_customer_date_images = 'api2/get_customer_date_images';
export const update_request = 'api2/update_request';
export const set_dnd = 'api2/set_dnd';
export const get_user_details = 'api2/get_user_details';
export const send_gift = 'api2/send_gift';
export const send_friend_request = 'api2/send_friend_request';
export const complete_courses_live_astro = 'api/complete_courses_live_astro';
export const get_request = 'api/get_call_chat_req';

// Astrologer
export const performance_dashboard = 'WalletCalclation/performance_dashboard';
export const astrologer_login = 'user/astrologer_login.php';
export const astrologer_logout = 'api2/doctor_logout';
export const astrologer_dashboard = 'api/astrologer_dashboard'; 
export const change_status_call = 'api/changestatuscall';
export const change_status = 'api/changestatus';
export const get_following_list_astro = 'api/getfollowinglistastro';
export const create_blog = 'api2/create_blog';
export const get_blogs = 'api2/get_blogs';
export const delete_blog = 'api2/delete_blog';
export const toggle_blog = 'api2/toggle_blog';
export const astro_order_history = 'api/astroOrder_history';
export const update_intake_status = 'api/update_intake_status';
export const get_astrologer_offer = 'api2/get_astrologer_offer';
export const astrologer_offer = 'api2/astrologer_offer';
export const next_log_status = 'api/next_log_status';
export const get_boost_amount = 'api2/get_boost_amount';
export const boost_astrologer = 'api2/boost_astrologer';
export const get_astro_payments = 'api2/get_astro_payments';
export const call_waiting_user_list = 'api/call_waiting_user_list';
export const kundli_basic_details = 'api2/astro_details_user';
export const kundli_dosha = 'api2/all_dosha_user';
export const recent_chat_history = 'api/chatHistoryAstro';
export const kundli_numerology_detailes = 'api2/getNumeroTable_user';
export const customer_kundli_chart = 'api2/get_chart_user';
export const upload_voice_image_pdf = 'api/upload_voice';
export const create_free_remedy = 'api/create_free_remedy';
export const category_pooja_list = 'api/category_pooja_list';
export const schedule_a_pooja = 'api/schedule_a_pooja';
export const schedule_a_pooja_astro = 'api/schedule_a_pooja_astro';
export const go_live_astro = 'api/go_live_astro';
export const exit_live_astro = 'api/exit_live_astro';
export const pooja_booking_customer_detail =
  'api/pooja_booking_customer_detail';
export const pooja_upload_attachments_video =
  'api/pooja_upload_attachments_video';
export const pooja_upload_attachments = 'api/pooja_upload_attachments';
export const astro_history_pooja = 'api/astro_history_pooja';
export const get_mall_cat = 'api/get_mall_cat';
export const schedule_a_pooja_id = 'api/schedule_a_pooja_id';
export const create_live_astrologer = 'api/create_live_astrologer';
export const go_live_astro_event = 'api/go_live_astro_event';
export const live_astro_id_list = 'api/live_astro_id_list';
export const update_mobile_mumber = 'AstroController/mobileNoUpdate';
export const upload_gallery_photo = 'AstroController/uploadImage';
export const get_gallery_photo = 'AstroController/getImage';
export const update_gallery_photo_status = 'AstroController/updateImageStatus';
export const delete_gallery_photo_status = 'AstroController/deleteImage';
export const get_followers = 'AstroController/getFollowers';
export const get_PDF = 'AstroController/getAstrologerPdf';
export const get_provider_details = 'AstroController/getAstrologerDetails';
export const update_bank_details = 'api/astro_bank_detail_update';
export const refer_an_astrologer = 'api/astrologer_inquiry';
export const get_all_offers = 'api/chat_call_discount'; 
export const update_offer_status = 'api/chat_call_discount_status';
export const upload_free_pdf = 'api/pdf_course';
export const post_mall_sub_category = 'api/post_mall_sub_category';
export const course_list = 'api/course_list';
export const demo_class = 'api/demo_class';
export const live_class = 'api/live_class';
export const moa_update = 'WalletCalclation/moaUpdate';
export const trending_astrologer = 'WalletCalclation/trending_astrologer';
export const deductwallet_chat = 'api/deductwallet_chat';
export const call_history_astro = 'WalletCalclation/call_history_astro';
export const chat_history_astro = 'WalletCalclation/chat_history_astro';
export const astro_all_wallet_history =
  'WalletCalclation/astro_all_wallet_history';
export const astro_all_wallet_history_new =
  'WalletCalclation/astro_all_wallet_history_new';
export const live_class_according_id = 'api/live_class_according_id';
export const pdf_course_demo_astro = 'api/pdf_course_demo_astro';
export const pdf_course_live_astro = 'api/pdf_course_live_astro';
export const traning_reel_astro_id = 'api/traning_reel_astro_id';
export const complete_course_live = 'api/complete_course_live';
export const complete_course_demo = 'api/complete_course_demo';
export const pdf_course_demo_astro_history =
  'api/pdf_course_demo_astro_history';
export const complete_course_demo_islive = 'api/complete_course_demo_islive';
export const complete_course_live_islive = 'api/complete_course_live_islive';
export const privacy_policy_astrologer = 'api/privacy_policy_astrologer';
export const terms = 'api/terms';
export const deductWallet_live_astro = 'api/deductWallet_live_astro'
export const footer_slider_astrologer = 'api/footer_slider_astrologer'
export const feedback_astro_application = 'api/feedbackAstroApplication'
export const remedy_list = 'api/remedy_list'
export const api2_get_birth_details = 'api2/birth_details';
export const api2_get_astro_detail = 'api2/astro_detail';
export const api2_get_horo_chart = 'api2/get_horo_chart';
export const api2_get_planet_details = 'api2/get_planets';
export const get_fav = 'api2/basic_numerology';
export const api2_get_kp_chart = 'api2/bhav_chalit_chart'
export const api2_get_house_report = 'api2/house_report';
export const api2_get_house_cusps = 'api2/house_cusps';
export const api2_get_house_ruling = 'api2/ruling_planet';
export const api2_get_planets = 'api2/get_planets';
export const api2_get_manglik_dosha = 'api2/check_manglik';
export const api2_get_kalsarph_dosha = 'api2/kalsarpa_dosha';
export const api2_get_sadhesati_status = 'api2/sadhesati_status';
export const api2_get_rudraksha_sugg = 'api2/rudraksha_suggestion';
export const api2_get_gemstone_sugg = 'api2/gem_suggestion';
export const api2_get_vdasha = 'api2/major_vdasha';
export const api2_get_sub_vdasha = 'api2/sub_vdasha';
export const api2_get_sub_sub_vdasha = 'api2/sub_sub_vdasha';
export const api2_get_sub_sub_sub_vdasha = 'api2/sub_sub_sub_vdasha';
export const api2_get_sub_sub_sub_sub_vdasha = 'api2/sub_sub_sub_sub_vdasha';
export const api2_get_current_vdasha = 'api2/current_vdasha';

export const google_map_key = 'AIzaSyAFNT2AARTumNCG0PLYcekBji6F-t30AhA';
export const call_app_id = 1928061131;
export const call_app_sign =
  '0c8f27bb3294208a5ccef0b14fa8f8989c3c753ebd2a8c8e696f04ceeb3afffd';
export const live_streaming_app_id = 587173410;
export const live_streaming_app_sign =
  '011d0941bcf41787bd3754dcc449dcbf45898eb89aa26dddf276f58592d6efdd';
