export const SET_PROVIDER_DATA = 'SET_PROVIDER_DATA';
export const SET_DASHBOARD = 'SET_DASHBOARD';
export const SET_FIREBASE_ID = 'SET_FIREBASE_ID';
export const SET_CHAT_REQUEST = 'SET_CHAT_REQUEST';
export const CLEAN_STORE = 'CLEAN_STORE';
export const IS_LOADING = 'IS_LOADING';
export const SET_LIVE_CLASS_COMMENTS = 'SET_LIVE_CLASS_COMMENTS';

